### ISSUE TITLE
mount s3fs to minio by user

### ISSUE THREAD

**Issue by smilelikeshit** [minio/cookbook#244] opened 2019-01-23 15:12 UTC
hi dev

im already successfully mount using s3fs on ubuntu 16.04
but by user can't create file on destination bucket from minio server.
any suggest if user ubuntu can write to folder minio mount by s3fs.

thank you

**Comment by kannappanr** [comment] 2019-01-24 02:16
@smilelikeshit Are you saying that you are unable to create a file on the destination bucket?

**Comment by kannappanr** [comment] 2019-01-29 18:38
@eco-minio Can you check the instructions given in the cookbook?

**Comment by deekoder** [comment] 2019-02-06 23:08
@smilelikeshit, Since it's not reproing on our end, I will go ahead and close this as "working as intended". Please feel free to reopen if you think it's still happening for you. We will be able to take a look.

**Closed by deekoder** 2019-02-06 23:08 UTC
Labels: priority: medium, working as intended
