### ISSUE TITLE
minio not accessible from outside (docker swarm deployment docs)

### ISSUE THREAD

**Issue by hadifarnoud** [minio/cookbook#222] opened 2018-07-13 06:58 UTC
I followed official docker swarm deployment docs [here](https://docs.minio.io/docs/deploy-minio-on-docker-swarm.html) 

I cannot access minio web browser on port 9000. neither does `mc` client works. 
`9000: connect: connection refused`

I disabled ufw and there is no firewall set up on my server. logs show minio is running

```
root@minio ~ # docker service logs minio_stack_minio1
minio_stack_minio1.1.6zmtbua56jef@minio    | Created minio configuration file successfully at /root/.minio
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Waiting for a minimum of 2 disks to come online (elapsed 0s)
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Waiting for a minimum of 2 disks to come online (elapsed 2s)
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Waiting for a minimum of 2 disks to come online (elapsed 3s)
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Waiting for a minimum of 2 disks to come online (elapsed 4s)
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Waiting for all other servers to be online to format the disks.
minio_stack_minio1.1.6zmtbua56jef@minio    | Status:         4 Online, 0 Offline.
minio_stack_minio1.1.6zmtbua56jef@minio    | Endpoint:  http://10.0.0.6:9000  http://10.255.0.6:9000  http://10.0.0.5:9000  http://10.255.0.5:9000  http://172.19.0.4:9000  http://127.0.0.1:9000
minio_stack_minio1.1.6zmtbua56jef@minio    | AccessKey: ***
minio_stack_minio1.1.6zmtbua56jef@minio    | SecretKey: ***
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Browser Access:
minio_stack_minio1.1.6zmtbua56jef@minio    |    http://10.0.0.6:9000  http://10.255.0.6:9000  http://10.0.0.5:9000  http://10.255.0.5:9000  http://172.19.0.4:9000  http://127.0.0.1:9000
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
minio_stack_minio1.1.6zmtbua56jef@minio    |    $ mc config host add myminio http://10.0.0.6:9000 ******* ********
minio_stack_minio1.1.6zmtbua56jef@minio    |
minio_stack_minio1.1.6zmtbua56jef@minio    | Object API (Amazon S3 compatible):
minio_stack_minio1.1.6zmtbua56jef@minio    |    Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
minio_stack_minio1.1.6zmtbua56jef@minio    |    Java:       https://docs.minio.io/docs/java-client-quickstart-guide
minio_stack_minio1.1.6zmtbua56jef@minio    |    Python:     https://docs.minio.io/docs/python-client-quickstart-guide
minio_stack_minio1.1.6zmtbua56jef@minio    |    JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
minio_stack_minio1.1.6zmtbua56jef@minio    |    .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
```

what did I do wrong? is that tutorial incomplete?

**Comment by hadifarnoud** [comment] 2018-07-13 07:55
I can access web ui on port 9001 to 9004

**Comment by nitisht** [comment] 2018-07-13 08:04
great. this is because the sample yaml file exposes ports 9001-9004 corresponding to each minio service

**Comment by nitisht** [comment] 2018-07-13 08:39
closing as working as intended

**Closed by nitisht** 2018-07-13 08:39 UTC

**Comment by hadifarnoud** [comment] 2018-07-13 09:30
isn't it supposed to be a distributed deployment and work on single port of 9000? this doc is slightly confusing.

most minio docs are just for quick start. this one was more like a production deployment tutorial

**Comment by nitisht** [comment] 2018-07-13 09:37
> this doc is slightly confusing.

actually the [doc](https://docs.minio.io/docs/deploy-minio-on-docker-compose.html) clearly mentions this 

`Minio services in the Docker compose file expose ports 9001 to 9004. This allows multiple services to run on a host.`

> isn't it supposed to be a distributed deployment and work on single port of 9000?

This allows flexibility to run on one/two/three or four nodes. If we map docker port 9000 to 9000 on the host - only one container can run on that host. You can easily change the yaml if that is what you intend to do.

**Comment by hadifarnoud** [comment] 2018-07-13 13:47
if that is the case and buckets are shared between nodes, I need to loadbalance it on port 9000. I assume that is the point one having different endpoints.

**Comment by hadifarnoud** [comment] 2018-08-17 14:39
I have another question, this setup creates four copies of exact same data on one server. what's the point? if it was four different servers, that makes sense for keeping replica somewhere else.

I have four volumes in `/var/lib/docker/volumes` with same data and this is eating up my disk space. how can I remove two of them?
