### ISSUE TITLE
Monitoring Minio Cluster

### ISSUE THREAD

**Issue by GPConnect** [minio/cookbook#245] opened 2019-02-08 18:54 UTC
hello, 
i installed on four hosts minio binary to start a cluster and use a load balancer to connect to it !
i tried to monitor each of the minio node with prometheus but only one came up !
is it the intended behavior ? should i get metrics from the load balancer instead ? 
Thanks

**Comment by harshavardhana** [comment] 2019-02-09 09:16
Each node provides it's own metrics .

**Comment by deekoder** [comment] 2019-02-19 19:14
Hope this answers your question @GPConnect. Closing this issue as working as intended.

**Closed by deekoder** 2019-02-19 19:14 UTC
Labels: priority: medium, working as intended

**Comment by GPConnect** [comment] 2019-02-20 22:55
Yes thanks, it was a network issue from my part !

Le mar. 19 févr. 2019 à 15:14, Dee Koder <notifications@github.com> a
écrit :
